name: Action

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Continuous Integration
        run: |
          docker build . -t {{ secrets.DOCKER_USERNAME }}/mc_g:latest
          docker login -u {{ secrets.DOCKER_USERNAME }} -p {{ secrets.DOCKER_PASSWORD }}
          docker push {{ secrets.DOCKER_USERNAME }}/mc_g:latest